bb-beagle-flasher (1.20240718.0)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/bb-beagle-flasher/suite/bullseye/debian/beagle-flasher-mv-rootfs-to-sda b/bb-beagle-flasher/suite/bullseye/debian/beagle-flasher-mv-rootfs-to-sda
--- a/bb-beagle-flasher/suite/bullseye/debian/beagle-flasher-mv-rootfs-to-sda
+++ b/bb-beagle-flasher/suite/bullseye/debian/beagle-flasher-mv-rootfs-to-sda
@@ -1,7 +1,8 @@
 #!/bin/bash -e
 
 if ! id | grep -q root; then
-	echo "must be run as root:"
+	echo "beagle-flasher-mv-rootfs-to-sda must be run as root:"
+	echo "sudo beagle-flasher-mv-rootfs-to-sda"
 	exit
 fi
 
@@ -115,17 +116,6 @@ broadcast_over_display () {
 }
 
 example_failure () {
-	message="Example: /etc/default/beagle-flasher"                                             ; broadcast
-	message="--------------------------------------------------------------------------------" ; broadcast
-	message="source=/dev/mmcblk0"                                                              ; broadcast
-	message="destination=/dev/mmcblk1"                                                         ; broadcast
-	message="rfs_partition=dual"                                                               ; broadcast
-	message="rfs_boot_startmb=1"                                                               ; broadcast
-	message="rfs_boot_size_mb=256"                                                             ; broadcast
-	message="bootloader=/opt/u-boot/bb-u-boot-beagleboneai64/install-emmc.sh"                  ; broadcast
-	message="flash_back=bbai64-emmc-to-microsd"                                                ; broadcast
-	message="extlinux=/opt/u-boot/bb-u-boot-beagleboneai64/emmc-extlinux.conf"                 ; broadcast
-	message="--------------------------------------------------------------------------------" ; broadcast
 	exit 2
 }
 
@@ -155,29 +145,11 @@ write_failure () {
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 	if [ "x${destination}" != "x" ] ; then
-		umount ${destination}p1 > /dev/null 2>&1 || true
+		umount ${destination}1 > /dev/null 2>&1 || true
 	fi
 }
 
 check_running_system () {
-	message="INFO: Giving system time to stablize..."                                          ; broadcast
-	message="--------------------------------------------------------------------------------" ; broadcast
-	message="5"                                                                                ; broadcast
-	sleep 1
-	message="4"                                                                                ; broadcast
-	sleep 1
-	message="3"                                                                                ; broadcast
-	sleep 1
-	message="2"                                                                                ; broadcast
-	sleep 1
-	message="1"                                                                                ; broadcast
-	sleep 1
-	message="--------------------------------------------------------------------------------" ; broadcast
-
-	message="INFO: Preparing /tmp"                                                             ; broadcast
-	message="INFO: [mount -t tmpfs tmpfs /tmp]"                                                ; broadcast
-	mount -t tmpfs tmpfs /tmp
-	message="--------------------------------------------------------------------------------" ; broadcast
 
 	message="INFO: /proc/cmdline"                                                              ; broadcast
 	message="INFO: [cat /proc/cmdline]"                                                        ; broadcast
@@ -220,6 +192,28 @@ check_running_system () {
 	else
 		message="INFO: [destination=${destination}] is a valid block device"                       ; broadcast
 	fi
+
+	if [ ! -f /boot/config-$(uname -r) ] ; then
+		zcat /proc/config.gz > /boot/config-$(uname -r) || true
+		message="INFO: Creating: [/boot/config-$(uname -r)]"                                       ; broadcast
+	else
+		message="INFO: [/boot/config-$(uname -r)]"                                                 ; broadcast
+	fi
+
+	if [ -f /usr/sbin/update-initramfs ] ; then
+		message="INFO: Generating: [/boot/initrd.img-$(uname -r)]"                                         ; broadcast
+		message="update-initramfs: Generating /boot/initrd.img-$(uname -r)"                                ; broadcast_over_display
+		if [ -f /boot/initrd.img-$(uname -r) ] ; then
+			update-initramfs -u -k $(uname -r) || true
+			message="--------------------------------------------------------------------------------" ; broadcast
+		else
+			update-initramfs -c -k $(uname -r) || true
+			message="--------------------------------------------------------------------------------" ; broadcast
+		fi
+		if [ -f /boot/firmware/initrd.img ] ; then
+			cp -v /boot/initrd.img-$(uname -r) /boot/firmware/initrd.img
+		fi
+	fi
 	flush_cache
 
 	if [ -f /etc/default/generic-sys-mods ] ; then
@@ -232,58 +226,45 @@ check_running_system () {
 }
 
 format_boot () {
-	message="mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}"                          ; broadcast
-	LC_ALL=C mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}
+	message="mkfs.vfat -F 16 ${destination}1 -n ${boot_label}"                          ; broadcast
+	LC_ALL=C mkfs.vfat -F 16 ${destination}1 -n ${boot_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
 format_root () {
-	message="mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}"              ; broadcast
-	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}
+	message="mkfs.ext4 ${ext4_options} ${destination}${dest_rfs_part} -L ${rootfs_label}"              ; broadcast
+	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}${dest_rfs_part} -L ${rootfs_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
 format_single_root () {
-	message="mkfs.ext4 ${ext4_options} ${destination}p1 -L ${single_root_label}"         ; broadcast
-	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}p1 -L ${single_root_label}
+	message="mkfs.ext4 ${ext4_options} ${destination}1 -L ${single_root_label}"         ; broadcast
+	LC_ALL=C mkfs.ext4 ${ext4_options} ${destination}1 -L ${single_root_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
-copy_boot () {
-	message="Copying: ${source}p1 -> ${destination}p1" ; broadcast
-	mount ${source}p1 /boot/firmware || true
-	mkdir -p /tmp/boot/ || true
-
-	mount ${destination}p1 /tmp/boot/ -o sync
-
-	message="rsync: (-aHAXx) /boot/firmware/ -> /tmp/boot/" ; broadcast
-	rsync -aHAXx --human-readable --info=progress2 /boot/firmware/ /tmp/boot/ || write_failure
-	flush_cache
+copy_boot_extlinux () {
+	message="Updating extlinux.conf" ; broadcast
 
 	if [ -f ${extlinux} ] ; then
-		message="INFO: [/boot/extlinux/extlinux.conf]"                                             ; broadcast
-		mkdir -p /tmp/boot/extlinux/ || true
-		cp -v ${extlinux} /tmp/boot/extlinux/extlinux.conf
-		message="INFO: [cat /tmp/boot/extlinux/extlinux.conf]"                                     ; broadcast
-		message="`cat /tmp/boot/extlinux/extlinux.conf`"                                           ; broadcast
+		message="INFO: [/boot/firmware/extlinux/extlinux.conf]"                                             ; broadcast
+		cp -v ${extlinux} /boot/firmware/extlinux/extlinux.conf
+		message="INFO: [cat /boot/firmware/extlinux/extlinux.conf]"                                     ; broadcast
+		message="`cat /boot/firmware/extlinux/extlinux.conf`"                                           ; broadcast
 		message="--------------------------------------------------------------------------------" ; broadcast
 	fi
 	flush_cache
-
-	umount /tmp/boot/ || umount -l /tmp/boot/ || write_failure
-	flush_cache
-	umount /boot/firmware || umount -l /boot/firmware || true
 }
 
 copy_rootfs () {
-	message="INFO: Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part}"       ; broadcast
+	message="INFO: Copying: ${source}p${src_rfs_part} -> ${destination}${dest_rfs_part}"       ; broadcast
 	mkdir -p /tmp/rootfs/ || true
 
-	message="INFO: [mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime]"       ; broadcast
-	mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime
+	message="INFO: [mount ${destination}${dest_rfs_part} /tmp/rootfs/ -o async,noatime]"       ; broadcast
+	mount ${destination}${dest_rfs_part} /tmp/rootfs/ -o async,noatime
 
 	message="INFO: rsync: (-aHAXx) [/ -> /tmp/rootfs/]"                                ; broadcast
 	rsync -aHAXx --human-readable --info=progress2 /* /tmp/rootfs/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/media/*,/lost+found,/lib/modules/*,/boot/firmware/*} || write_failure
@@ -305,12 +286,10 @@ copy_rootfs () {
 	message="INFO: Generating: /etc/fstab"                                                     ;  broadcast
 	echo "# /etc/fstab: static file system information." > /tmp/rootfs/etc/fstab
 	echo "#" >> /tmp/rootfs/etc/fstab
-	echo "${destination}p${dest_rfs_part}  /  ext4  noatime,errors=remount-ro  0  1" >> /tmp/rootfs/etc/fstab
-	if [ "x${dest_rfs_part}" = "x2" ] || [ "x${dest_rfs_part}" = "x3" ] ; then
-		echo "${destination}p1  /boot/firmware vfat ${rfs_boot_permissions} 0 0" >> /tmp/rootfs/etc/fstab
-	fi
+	echo "${destination}${dest_rfs_part}  /  ext4  noatime,errors=remount-ro  0  1" >> /tmp/rootfs/etc/fstab
+	echo "${source}p1  /boot/firmware vfat ${rfs_boot_permissions} 0 0" >> /tmp/rootfs/etc/fstab
 	if [ "x${rfs_swap_size_mb}" != "x" ] ; then
-		echo "${destination}p2  none    swap    sw      0       0" >>/tmp/rootfs/etc/fstab
+		echo "${destination}1  none    swap    sw      0       0" >>/tmp/rootfs/etc/fstab
 	fi
 	echo "debugfs  /sys/kernel/debug  debugfs  mode=755,uid=root,gid=gpio,defaults  0  0" >> /tmp/rootfs/etc/fstab
 	message="INFO: [cat /tmp/rootfs/etc/fstab]"                                                ; broadcast
@@ -318,59 +297,18 @@ copy_rootfs () {
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 
-	if [ "x${flash_back}" != "x" ] ; then
-		if [ -f ${flash_back} ] ; then
-			message="INFO: [cp -v ${flash_back} /tmp/rootfs/etc/default/beagle-flasher]" ; broadcast
-			cp -v ${flash_back} /tmp/rootfs/etc/default/beagle-flasher
-			message="--------------------------------------------------------------------------------" ; broadcast
-		else
-			if [ -f /etc/beagle-flasher/${flash_back} ] ; then
-				message="INFO: [cp -v /etc/beagle-flasher/${flash_back} /tmp/rootfs/etc/default/beagle-flasher]" ; broadcast
-				cp -v /etc/beagle-flasher/${flash_back} /tmp/rootfs/etc/default/beagle-flasher
-				message="--------------------------------------------------------------------------------" ; broadcast
-			fi
-		fi
-	fi
-
-	if [ -f /tmp/rootfs/etc/default/generic-sys-mods ] ; then
-		. /tmp/rootfs/etc/default/generic-sys-mods
-
-		echo "#This file is sourced by /usb/bin/bb-growpart" > /tmp/rootfs/etc/default/generic-sys-mods
-		echo "ROOT_DRIVE=${destination}" >> /tmp/rootfs/etc/default/generic-sys-mods
-		echo "ROOT_PARTITION=${dest_rfs_part}" >> /tmp/rootfs/etc/default/generic-sys-mods
-		echo "ARCH_SOC_MODULES=${ARCH_SOC_MODULES}" >> /tmp/rootfs/etc/default/generic-sys-mods
-
-		message="INFO: [cat /tmp/rootfs/etc/default/generic-sys-mods]"                             ; broadcast
-		message="`cat /tmp/rootfs/etc/default/generic-sys-mods`"                                   ; broadcast
-		message="--------------------------------------------------------------------------------" ; broadcast
-	fi
-
 	if [ -f /tmp/rootfs/etc/systemd/system/multi-user.target.wants/grow_partition.service ] ; then
 		rm -rf /tmp/rootfs/etc/systemd/system/multi-user.target.wants/grow_partition.service || true
 	fi
 	flush_cache
 
-	if [ "x${flash_cc1352p}" = "xenable" ] ; then
-		if [ -f /usr/share/beagleconnect/firmware/0.2.2/play/cc2538-bsl.py ] ; then
-			/usr/share/beagleconnect/firmware/0.2.2/play/cc2538-bsl.py /usr/share/beagleconnect/firmware/0.2.2/play/wpanusb/ &> /tmp/rootfs/var/log/cc2538.log
-			cat /tmp/rootfs/var/log/cc2538.log
-			mac=$(cat /tmp/rootfs/var/log/cc2538.log | grep '^Primary IEEE Address:' | awk -F 'Address: ' '{print $2}' || true)
-			echo "MACADDR=${mac}" >> /tmp/rootfs/etc/default/lowpan
-		fi
-	fi
-
-	message="Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part} complete"    ; broadcast
+	message="Copying: ${source}p${src_rfs_part} -> ${destination}${dest_rfs_part} complete"    ; broadcast
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 
 	message="INFO: [umount /tmp/rootfs/ || umount -l /tmp/rootfs/ || write_failure]"           ; broadcast
 	umount /tmp/rootfs/ || umount -l /tmp/rootfs/ || write_failure
 	message="--------------------------------------------------------------------------------" ; broadcast
-
-	message="INFO: [umount /tmp || true]"                                                      ; broadcast
-	umount /tmp || true
-	message="--------------------------------------------------------------------------------" ; broadcast
-	flush_cache
 
 	message="INFO: Force writeback of eMMC buffers by Syncing: ${destination}"                 ; broadcast
 	message="INFO: [dd if=${destination} of=/dev/null count=100000 status=progress]"           ; broadcast
@@ -380,47 +318,6 @@ copy_rootfs () {
 
 	if [ "x${has_usr_leds}" = "xenable" ] ; then
 		reset_leds
-	fi
-
-	unset are_we_flasher
-	are_we_flasher=$(grep init-beagle-flasher /proc/cmdline || true)
-	if [ ! "x${are_we_flasher}" = "x" ] ; then
-		message="INFO: [We are init, trying to shutdown, we may crash, data is RO so safe]" ; broadcast
-		message="5"                                                                                ; broadcast
-		sleep 1
-
-		if [ -f /proc/sysrq-trigger ] ; then
-			message="INFO: [found: /proc/sysrq-trigger]" ; broadcast
-			message="INFO: [found: echo s > /proc/sysrq-trigger" ; broadcast
-			message="INFO: [found: echo o > /proc/sysrq-trigger" ; broadcast
-			message="4"                                                                                ; broadcast
-			sleep 1
-			message="3"                                                                                ; broadcast
-			sleep 1
-			message="2"                                                                                ; broadcast
-			sleep 1
-			message="1"                                                                                ; broadcast
-			sleep 1
-			message="--------------------------------------------------------------------------------" ; broadcast
-			#For sync
-			echo s > /proc/sysrq-trigger
-			#For shutdown the system
-			echo o > /proc/sysrq-trigger
-		fi
-
-		message="4"                                                                                ; broadcast
-		sleep 1
-		message="3"                                                                                ; broadcast
-		sleep 1
-		message="2"                                                                                ; broadcast
-		sleep 1
-		message="1"                                                                                ; broadcast
-		sleep 1
-		message="--------------------------------------------------------------------------------" ; broadcast
-
-		#When run as init
-		exec /sbin/init
-		exit #We should not hit that
 	fi
 }
 
@@ -449,8 +346,8 @@ partition_drive () {
 
 	rfs_boot_permissions=${rfs_boot_permissions:-"defaults"}
 
-	if [ "x${rfs_partition}" = "xsingle" ] ; then
-		partition_one_start_mb=${rfs_rootfs_startmb:-"4"}
+	if [ "x${rfs_partition}" = "xhybrid" ] ; then
+		partition_one_start_mb=${rfs_rootfs_startmb:-"1"}
 		partition_one_fstype=${rfs_sfdisk_fstype:-"L"}
 
 		single_root_label=${single_root_label:-"rootfs"}
@@ -473,8 +370,49 @@ partition_drive () {
 		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
 		message="--------------------------------------------------------------------------------" ; broadcast
 
-		src_rfs_part=${src_rfs_part:-"1"}
-		dest_rfs_part="1"
+		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
+			src_rfs_part=${src_rfs_part:-"3"}
+			dest_rfs_part="1"
+		else
+			src_rfs_part=${src_rfs_part:-"2"}
+			dest_rfs_part="1"
+		fi
+		copy_boot_extlinux
+		copy_rootfs
+	elif [ "x${rfs_partition}" = "xhybrid_swap" ] ; then
+		partition_one_start_mb=${rfs_boot_startmb:-"1"}
+		partition_one_size_mb="${rfs_swap_size_mb}"
+		partition_one_fstype=${rfs_sfdisk_fstype:-"0x82"}
+
+		partition_two_start_mb=$(($partition_one_start_mb + $partition_one_size_mb))
+
+		rootfs_label=${rootfs_label:-"rootfs"}
+		sfdisk_options="--force --wipe-partitions always"
+
+		message="INFO: Partitioning: ${destination}"                                               ; broadcast
+		message="INFO: sfdisk: [$(LC_ALL=C sfdisk --version)]"                         ; broadcast
+		message="INFO: sfdisk: [sfdisk ${sfdisk_options} ${destination}]"              ; broadcast
+		message="INFO: sfdisk: [${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},-]" ; broadcast
+		message="INFO: sfdisk: [${partition_two_start_mb}M,,,-]" ; broadcast
+		message="--------------------------------------------------------------------------------" ; broadcast
+
+		LC_ALL=C sfdisk ${sfdisk_options} "${destination}" <<-__EOF__
+			${partition_one_start_mb}M,${partition_one_size_mb}M,${partition_one_fstype},-
+			${partition_two_start_mb}M,,,-
+		__EOF__
+
+		flush_cache
+
+		src_rfs_part=${src_rfs_part:-"3"}
+		dest_rfs_part="2"
+
+		message="INFO: Formatting: ${destination}"                                                 ; broadcast
+		format_root
+		LC_ALL=C mkswap ${destination}1
+		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
+		message="--------------------------------------------------------------------------------" ; broadcast
+
+		copy_boot_extlinux
 		copy_rootfs
 	elif [ "x${rfs_partition}" = "xdual" ] ; then
 		partition_one_start_mb=${rfs_boot_startmb:-"1"}
@@ -532,7 +470,7 @@ partition_drive () {
 		format_boot
 		format_root
 		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
-			LC_ALL=C mkswap ${destination}p2
+			LC_ALL=C mkswap ${destination}2
 		fi
 		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
 		message="--------------------------------------------------------------------------------" ; broadcast
